name: Go
on: [push]
jobs:

  build:
    name: Build & Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Set up staticcheck
        run: go get -v honnef.co/go/tools/cmd/staticcheck

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Build
        run: go build -v -mod=vendor .

      - name: Test
        run: go test -v -mod=vendor -race ./...
